language: python
python:
    - "2.7"
    - "2.6"

branches:
    only:
        - master

git:
    submodules: false

before_script:
    - sudo apt-get update
    - sudo apt-get install -y --force-yes protobuf-compiler python-protobuf
    - make -C tko

install:
    - pip install sphinx tox simplejson MySQL-python
    - pip install -r requirements-travis.txt

script:
    - ./utils/unittest_suite_nose.py -c .nose.cfg
    - rm -f tko/tko_pb2.py
    - inspekt checkall --disable-lint W,R,C,E0012,E1002,E1101,E1103,E1120,F0401,I0011 --exclude frontend/apache_auth.py --no-license-check

notifications:
  irc:
    channels: "irc.oftc.net#autotest"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
